name: 🍭 Pull Request (ID)
description: Kirim perubahan atau penambahan fitur ke repositori
title: "[PR] "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: 🍰 Deskripsi Perubahan
      description: Jelaskan secara singkat apa yang ditambahkan atau diubah dalam PR ini.
      placeholder: 'Contoh: "Menambahkan fallback API untuk fitur .hd"'
    validations:
      required: true

  - type: checkboxes
    id: change-type
    attributes:
      label: 🍡 Jenis Perubahan
      description: Pilih yang sesuai
      options:
        - label: 🐞 Perbaikan bug
        - label: ✨ Fitur baru
        - label: 🧹 Refactor / pembersihan kode
        - label: 📚 Pembaruan dokumentasi
        - label: 🔧 Perubahan konfigurasi / setup

  - type: checkboxes
    id: checklist
    attributes:
      label: 🧁 Checklist
      description: Pastikan kamu sudah melakukan hal berikut
      options:
        - label: Kode sudah diuji dan berjalan sesuai harapan
          required: true
        - label: Tidak ada error saat build atau dijalankan
          required: true
        - label: Mengikuti gaya penulisan kode Liora
          required: true
        - label: Dokumentasi diperbarui jika diperlukan

  - type: textarea
    id: additional-notes
    attributes:
      label: 🍬 Catatan Tambahan
      description: Konteks atau catatan penting lainnya
      placeholder: 'Contoh: "PR ini menyentuh auth.js, mohon dicek dengan seksama."'