whatsapp:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*"
          - "lib/core/**/*"
          - "lib/auth/**/*"

api:
  - changed-files:
      - any-glob-to-any-file: "lib/api/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"
          - "**/*.md"
          - "README.md"
          - "CHANGELOG.md"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.json"
          - "*.yml"
          - "*.yaml"
          - ".github/**/*"

ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
          - ".github/actions/**/*"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "bun.lockb"

security:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*security*"
          - ".github/workflows/*scan*"