whatsapp:
    changed-files:
        - any-glob-to-any-file:
              - "src/*"
              - "src/lib/core/*"

api:
    changed-files:
        - any-glob-to-any-file: "src/lib/api/**/*"

documentation:
    changed-files:
        - any-glob-to-any-file:
              - "**/*.md"
              - "README.md"

config:
    changed-files:
        - any-glob-to-any-file:
              - "*.json"
              - "*.yml"
              - "*.yaml"
              - ".github/**/*"

database:
    changed-files:
        - any-glob-to-any-file: "src/lib/core/auth/*"

ci-cd:
    changed-files:
        - any-glob-to-any-file: ".github/workflows/**/*"

dependencies:
    changed-files:
        - any-glob-to-any-file:
              - "package.json"
              - "bun.lockb"

security:
    changed-files:
        - any-glob-to-any-file:
              - ".github/workflows/security/**/*"
              - ".github/workflows/scan/**/*"
