javascript:
    - changed-files:
        - any-glob-to-any-file: ['src/**/*.js', 'lib/**/*.js', '*.js']

rust:
    - changed-files:
        - any-glob-to-any-file: ['lib/rs/**/*.rs', 'lib/rs/**/Cargo.toml', 'lib/rs/**/Cargo.lock']

cpp:
    - changed-files:
        - any-glob-to-any-file: ['lib/cpp/**/*.cpp', 'lib/cpp/**/*.h', 'lib/cpp/**/*.cc', 'binding.gyp']

documentation:
    - changed-files:
        - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

configuration:
    - changed-files:
        - any-glob-to-any-file: ['*.toml', '*.json', '*.yml', '*.yaml', '.github/**/*']

dependencies:
    - changed-files:
        - any-glob-to-any-file: ['package.json', 'bun.lockb', 'lib/rs/Cargo.lock']

plugins:
    - changed-files:
        - any-glob-to-any-file: ['plugins/**/*']

api:
    - changed-files:
        - any-glob-to-any-file: ['lib/api/**/*']

core:
    - changed-files:
        - any-glob-to-any-file: ['lib/core/**/*']

auth:
    - changed-files:
        - any-glob-to-any-file: ['lib/auth/**/*']

tests:
    - changed-files:
        - any-glob-to-any-file: ['**/*.test.js', '**/*.spec.js', 'lib/rs/tests/**/*']
